// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.DatabaseConfigs;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(SmartWarehouseDbContext))]
    partial class SmartWarehouseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ActionLog", b =>
                {
                    b.Property<int>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ActionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActionId"));

                    b.Property<string>("ActionType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ActionId")
                        .HasName("PK__ActionLo__FFE3F4B95252482B");

                    b.HasIndex("UserId");

                    b.ToTable("ActionLog", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.BusinessPartner", b =>
                {
                    b.Property<int>("PartnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PartnerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartnerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PartnerId")
                        .HasName("PK__Business__39FD63324D0693B4");

                    b.ToTable("BusinessPartner", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CycleCount", b =>
                {
                    b.Property<int>("CycleCountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CycleCountID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CycleCountId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CycleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.HasKey("CycleCountId")
                        .HasName("PK__CycleCou__A4189B51C1D19CDB");

                    b.ToTable("CycleCount", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CycleCountDetail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<int>("CheckedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CheckedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CountedQuantity")
                        .HasColumnType("int");

                    b.Property<int>("CycleCountId")
                        .HasColumnType("int")
                        .HasColumnName("CycleCountID");

                    b.Property<int?>("Difference")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("([CountedQuantity]-[SystemQuantity])", false);

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int>("SystemQuantity")
                        .HasColumnType("int");

                    b.HasKey("DetailId")
                        .HasName("PK__CycleCou__135C314D899B9755");

                    b.HasIndex("CheckedBy");

                    b.HasIndex("CycleCountId");

                    b.HasIndex("ProductId");

                    b.ToTable("CycleCountDetail", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ExportDetail", b =>
                {
                    b.Property<int>("ExportDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ExportDetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExportDetailId"));

                    b.Property<int>("ExportOrderId")
                        .HasColumnType("int")
                        .HasColumnName("ExportOrderID");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ExportDetailId")
                        .HasName("PK__ExportDe__07C903598CFEC015");

                    b.HasIndex("ExportOrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("ExportDetail", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ExportOrder", b =>
                {
                    b.Property<int>("ExportOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ExportOrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExportOrderId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Currency")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("ShippedAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("ShippedDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("TaxRate")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("TotalPayment")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ExportOrderId")
                        .HasName("PK__ExportOr__618D04DEB462B526");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CustomerId");

                    b.ToTable("ExportOrder", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ImportDetail", b =>
                {
                    b.Property<int>("ImportDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ImportDetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImportDetailId"));

                    b.Property<int>("ImportOrderId")
                        .HasColumnType("int")
                        .HasColumnName("ImportOrderID");

                    b.Property<decimal?>("ImportPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ImportDetailId")
                        .HasName("PK__ImportDe__CDFBBA51482A60DC");

                    b.HasIndex("ImportOrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("ImportDetail", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ImportOrder", b =>
                {
                    b.Property<int>("ImportOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ImportOrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImportOrderId"));

                    b.Property<DateOnly?>("ArrivalDate")
                        .HasColumnType("date");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ImportOrderId")
                        .HasName("PK__ImportOr__EAFFE3151D8202F1");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProviderId");

                    b.ToTable("ImportOrder", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InventoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryId"));

                    b.Property<int>("AllocatedQuantity")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("LocationID");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("InventoryId")
                        .HasName("PK__Inventor__F5FDE6D3CF9EDED3");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductId");

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LocationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<int?>("ColumnNumber")
                        .HasColumnType("int");

                    b.Property<bool?>("IsFull")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("RowNumber")
                        .HasColumnType("int");

                    b.Property<string>("ShelfId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ShelfID");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LocationId")
                        .HasName("PK__Location__E7FEA477F338D051");

                    b.ToTable("Location", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("ExpiredDate")
                        .HasColumnType("date");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("PurchasedPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateOnly>("ReceivedDate")
                        .HasColumnType("date");

                    b.Property<int?>("ReorderPoint")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ProductId")
                        .HasName("PK__Product__B40CC6ED4329EB44");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ReturnAction", b =>
                {
                    b.Property<int>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ActionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActionId"));

                    b.Property<string>("Action")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ActionId")
                        .HasName("PK__ReturnAc__FFE3F4B957EB09FD");

                    b.ToTable("ReturnAction", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ReturnOrder", b =>
                {
                    b.Property<int>("ReturnOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReturnOrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReturnOrderId"));

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("CheckedBy")
                        .HasColumnType("int");

                    b.Property<int?>("ExportOrderId")
                        .HasColumnType("int")
                        .HasColumnName("ExportOrderID");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ReturnOrderId")
                        .HasName("PK__ReturnOr__4DBF556378E06DEC");

                    b.HasIndex("CheckedBy");

                    b.HasIndex("ExportOrderId");

                    b.HasIndex("ReviewedBy");

                    b.ToTable("ReturnOrder", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ReturnOrderDetail", b =>
                {
                    b.Property<int>("ReturnDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReturnDetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReturnDetailId"));

                    b.Property<int?>("ActionId")
                        .HasColumnType("int")
                        .HasColumnName("ActionID");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("LocationID");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ReasonId")
                        .HasColumnType("int")
                        .HasColumnName("ReasonID");

                    b.Property<int>("ReturnOrderId")
                        .HasColumnType("int")
                        .HasColumnName("ReturnOrderID");

                    b.HasKey("ReturnDetailId")
                        .HasName("PK__ReturnOr__8B89C9EAC4864254");

                    b.HasIndex("ActionId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReasonId");

                    b.HasIndex("ReturnOrderId");

                    b.ToTable("ReturnOrderDetail", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ReturnReason", b =>
                {
                    b.Property<int>("ReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReasonID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReasonId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ReasonId")
                        .HasName("PK__ReturnRe__A4F8C0C7D482E53D");

                    b.ToTable("ReturnReason", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TransactionLog", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TransactionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("QuantityChanged")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TransactionId")
                        .HasName("PK__Transact__55433A4B8F2EB147");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProductId");

                    b.ToTable("TransactionLog", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CCAC8EA782E8");

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D10534577EB67D")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ActionLog", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("ActionLogs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__ActionLog__UserI__6E01572D");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.CycleCountDetail", b =>
                {
                    b.HasOne("Domain.Entities.User", "CheckedByNavigation")
                        .WithMany("CycleCountDetails")
                        .HasForeignKey("CheckedBy")
                        .IsRequired()
                        .HasConstraintName("FK__CycleCoun__Check__09A971A2");

                    b.HasOne("Domain.Entities.CycleCount", "CycleCount")
                        .WithMany("CycleCountDetails")
                        .HasForeignKey("CycleCountId")
                        .IsRequired()
                        .HasConstraintName("FK__CycleCoun__Cycle__07C12930");

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("CycleCountDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__CycleCoun__Produ__08B54D69");

                    b.Navigation("CheckedByNavigation");

                    b.Navigation("CycleCount");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.ExportDetail", b =>
                {
                    b.HasOne("Domain.Entities.ExportOrder", "ExportOrder")
                        .WithMany("ExportDetails")
                        .HasForeignKey("ExportOrderId")
                        .IsRequired()
                        .HasConstraintName("FK__ExportDet__Expor__5535A963");

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("ExportDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__ExportDet__Produ__5629CD9C");

                    b.Navigation("ExportOrder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.ExportOrder", b =>
                {
                    b.HasOne("Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("ExportOrders")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__ExportOrd__Creat__52593CB8");

                    b.HasOne("Domain.Entities.BusinessPartner", "Customer")
                        .WithMany("ExportOrders")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__ExportOrd__Custo__5165187F");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Domain.Entities.ImportDetail", b =>
                {
                    b.HasOne("Domain.Entities.ImportOrder", "ImportOrder")
                        .WithMany("ImportDetails")
                        .HasForeignKey("ImportOrderId")
                        .IsRequired()
                        .HasConstraintName("FK__ImportDet__Impor__4CA06362");

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("ImportDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__ImportDet__Produ__4D94879B");

                    b.Navigation("ImportOrder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.ImportOrder", b =>
                {
                    b.HasOne("Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("ImportOrders")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__ImportOrd__Creat__49C3F6B7");

                    b.HasOne("Domain.Entities.BusinessPartner", "Provider")
                        .WithMany("ImportOrders")
                        .HasForeignKey("ProviderId")
                        .IsRequired()
                        .HasConstraintName("FK__ImportOrd__Provi__48CFD27E");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Domain.Entities.Inventory", b =>
                {
                    b.HasOne("Domain.Entities.Location", "Location")
                        .WithMany("Inventories")
                        .HasForeignKey("LocationId")
                        .IsRequired()
                        .HasConstraintName("FK__Inventory__Locat__44FF419A");

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__Inventory__Produ__440B1D61");

                    b.Navigation("Location");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.ReturnOrder", b =>
                {
                    b.HasOne("Domain.Entities.User", "CheckedByNavigation")
                        .WithMany("ReturnOrderCheckedByNavigations")
                        .HasForeignKey("CheckedBy")
                        .HasConstraintName("FK__ReturnOrd__Check__5DCAEF64");

                    b.HasOne("Domain.Entities.ExportOrder", "ExportOrder")
                        .WithMany("ReturnOrders")
                        .HasForeignKey("ExportOrderId")
                        .HasConstraintName("FK__ReturnOrd__Expor__5CD6CB2B");

                    b.HasOne("Domain.Entities.User", "ReviewedByNavigation")
                        .WithMany("ReturnOrderReviewedByNavigations")
                        .HasForeignKey("ReviewedBy")
                        .HasConstraintName("FK__ReturnOrd__Revie__5EBF139D");

                    b.Navigation("CheckedByNavigation");

                    b.Navigation("ExportOrder");

                    b.Navigation("ReviewedByNavigation");
                });

            modelBuilder.Entity("Domain.Entities.ReturnOrderDetail", b =>
                {
                    b.HasOne("Domain.Entities.ReturnAction", "Action")
                        .WithMany("ReturnOrderDetails")
                        .HasForeignKey("ActionId")
                        .HasConstraintName("FK__ReturnOrd__Actio__6477ECF3");

                    b.HasOne("Domain.Entities.Location", "Location")
                        .WithMany("ReturnOrderDetails")
                        .HasForeignKey("LocationId")
                        .HasConstraintName("FK__ReturnOrd__Locat__656C112C");

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("ReturnOrderDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__ReturnOrd__Produ__628FA481");

                    b.HasOne("Domain.Entities.ReturnReason", "Reason")
                        .WithMany("ReturnOrderDetails")
                        .HasForeignKey("ReasonId")
                        .HasConstraintName("FK__ReturnOrd__Reaso__6383C8BA");

                    b.HasOne("Domain.Entities.ReturnOrder", "ReturnOrder")
                        .WithMany("ReturnOrderDetails")
                        .HasForeignKey("ReturnOrderId")
                        .IsRequired()
                        .HasConstraintName("FK__ReturnOrd__Retur__619B8048");

                    b.Navigation("Action");

                    b.Navigation("Location");

                    b.Navigation("Product");

                    b.Navigation("Reason");

                    b.Navigation("ReturnOrder");
                });

            modelBuilder.Entity("Domain.Entities.TransactionLog", b =>
                {
                    b.HasOne("Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("TransactionLogs")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Transacti__Creat__6A30C649");

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("TransactionLogs")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__Transacti__Produ__693CA210");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.BusinessPartner", b =>
                {
                    b.Navigation("ExportOrders");

                    b.Navigation("ImportOrders");
                });

            modelBuilder.Entity("Domain.Entities.CycleCount", b =>
                {
                    b.Navigation("CycleCountDetails");
                });

            modelBuilder.Entity("Domain.Entities.ExportOrder", b =>
                {
                    b.Navigation("ExportDetails");

                    b.Navigation("ReturnOrders");
                });

            modelBuilder.Entity("Domain.Entities.ImportOrder", b =>
                {
                    b.Navigation("ImportDetails");
                });

            modelBuilder.Entity("Domain.Entities.Location", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("ReturnOrderDetails");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Navigation("CycleCountDetails");

                    b.Navigation("ExportDetails");

                    b.Navigation("ImportDetails");

                    b.Navigation("Inventories");

                    b.Navigation("ReturnOrderDetails");

                    b.Navigation("TransactionLogs");
                });

            modelBuilder.Entity("Domain.Entities.ReturnAction", b =>
                {
                    b.Navigation("ReturnOrderDetails");
                });

            modelBuilder.Entity("Domain.Entities.ReturnOrder", b =>
                {
                    b.Navigation("ReturnOrderDetails");
                });

            modelBuilder.Entity("Domain.Entities.ReturnReason", b =>
                {
                    b.Navigation("ReturnOrderDetails");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("ActionLogs");

                    b.Navigation("CycleCountDetails");

                    b.Navigation("ExportOrders");

                    b.Navigation("ImportOrders");

                    b.Navigation("ReturnOrderCheckedByNavigations");

                    b.Navigation("ReturnOrderReviewedByNavigations");

                    b.Navigation("TransactionLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
